import 'reflect-metadata';
import { DataSource } from 'typeorm';
import { LoanProduct, LoanProductType } from '../../modules/loans/entities/loan-product.entity';

const dataSource = new DataSource({
  type:     'postgres',
  host:     process.env['POSTGRES_HOST']     ?? 'localhost',
  port:     parseInt(process.env['POSTGRES_PORT'] ?? '5432'),
  username: process.env['POSTGRES_USER']     ?? 'creditmap',
  password: process.env['POSTGRES_PASSWORD'] ?? 'creditmap_secret',
  database: process.env['POSTGRES_DB']       ?? 'creditmap_dev',
  entities: [LoanProduct],
  synchronize: false,
});

const PRODUCTS: Partial<LoanProduct>[] = [
  {
    lenderName:          'Grameen Koota',
    productName:         'Microfinance Loan',
    productType:         LoanProductType.MICROFINANCE,
    minScore:            300,
    maxScore:            850,
    minMonthlyIncome:    5000,
    loanAmountMin:       5000,
    loanAmountMax:       50000,
    interestRatePA:      '21.50',
    tenureMonthsMin:     12,
    tenureMonthsMax:     24,
    processingFeePercent: null,
    targetSegments:      ['daily_wage', 'gig', 'farm', 'self_employed'],
    applyUrl:            null,
    description:         'Microfinance loans for rural and semi-urban women entrepreneurs',
    isActive:            true,
  },
  {
    lenderName:          'Aroha Financial Services',
    productName:         'Personal Loan',
    productType:         LoanProductType.PERSONAL,
    minScore:            400,
    maxScore:            850,
    minMonthlyIncome:    8000,
    loanAmountMin:       10000,
    loanAmountMax:       100000,
    interestRatePA:      '18.00',
    tenureMonthsMin:     12,
    tenureMonthsMax:     36,
    processingFeePercent: '2.00',
    targetSegments:      ['gig', 'self_employed', 'daily_wage'],
    applyUrl:            null,
    description:         'Personal loans for gig workers and self-employed individuals',
    isActive:            true,
  },
  {
    lenderName:          'Muthoot Fincorp',
    productName:         'Gold Loan',
    productType:         LoanProductType.SECURED,
    minScore:            300,
    maxScore:            850,
    minMonthlyIncome:    null,
    loanAmountMin:       10000,
    loanAmountMax:       500000,
    interestRatePA:      '12.00',
    tenureMonthsMin:     6,
    tenureMonthsMax:     24,
    processingFeePercent: '0.50',
    targetSegments:      ['salaried', 'self_employed', 'farm', 'daily_wage', 'gig'],
    applyUrl:            null,
    description:         'Gold-secured loans — no income proof required, fast disbursal',
    isActive:            true,
  },
  {
    lenderName:          'CreditAccess Grameen',
    productName:         'Rural Business Loan',
    productType:         LoanProductType.MICROFINANCE,
    minScore:            350,
    maxScore:            850,
    minMonthlyIncome:    6000,
    loanAmountMin:       10000,
    loanAmountMax:       150000,
    interestRatePA:      '19.00',
    tenureMonthsMin:     12,
    tenureMonthsMax:     36,
    processingFeePercent: null,
    targetSegments:      ['farm', 'self_employed', 'daily_wage'],
    applyUrl:            null,
    description:         'MSME and farm credit for rural households',
    isActive:            true,
  },
  {
    lenderName:          'Jana Small Finance Bank',
    productName:         'Personal Loan',
    productType:         LoanProductType.PERSONAL,
    minScore:            500,
    maxScore:            850,
    minMonthlyIncome:    12000,
    loanAmountMin:       25000,
    loanAmountMax:       300000,
    interestRatePA:      '16.00',
    tenureMonthsMin:     12,
    tenureMonthsMax:     60,
    processingFeePercent: '2.00',
    targetSegments:      ['salaried', 'self_employed', 'gig'],
    applyUrl:            null,
    description:         'Personal loans with flexible EMIs for first-time borrowers',
    isActive:            true,
  },
  {
    lenderName:          'Ujjivan Small Finance Bank',
    productName:         'Personal Loan',
    productType:         LoanProductType.PERSONAL,
    minScore:            550,
    maxScore:            850,
    minMonthlyIncome:    15000,
    loanAmountMin:       50000,
    loanAmountMax:       500000,
    interestRatePA:      '14.50',
    tenureMonthsMin:     12,
    tenureMonthsMax:     60,
    processingFeePercent: '1.50',
    targetSegments:      ['salaried', 'self_employed'],
    applyUrl:            null,
    description:         'Salaried and self-employed personal loans with competitive rates',
    isActive:            true,
  },
  {
    lenderName:          'IIFL Finance',
    productName:         'Quick Personal Loan',
    productType:         LoanProductType.PERSONAL,
    minScore:            500,
    maxScore:            850,
    minMonthlyIncome:    12000,
    loanAmountMin:       10000,
    loanAmountMax:       200000,
    interestRatePA:      '17.00',
    tenureMonthsMin:     6,
    tenureMonthsMax:     36,
    processingFeePercent: '2.00',
    targetSegments:      ['salaried', 'self_employed', 'gig'],
    applyUrl:            null,
    description:         'Quick personal loans with minimal documentation',
    isActive:            true,
  },
  {
    lenderName:          'Fullerton India Credit',
    productName:         'Personal Loan',
    productType:         LoanProductType.PERSONAL,
    minScore:            600,
    maxScore:            850,
    minMonthlyIncome:    20000,
    loanAmountMin:       50000,
    loanAmountMax:       500000,
    interestRatePA:      '13.00',
    tenureMonthsMin:     12,
    tenureMonthsMax:     60,
    processingFeePercent: '1.50',
    targetSegments:      ['salaried', 'self_employed'],
    applyUrl:            null,
    description:         'Premium personal loans for established earners',
    isActive:            true,
  },
  {
    lenderName:          'InCred Finance',
    productName:         'Digital Personal Loan',
    productType:         LoanProductType.PERSONAL,
    minScore:            550,
    maxScore:            850,
    minMonthlyIncome:    18000,
    loanAmountMin:       25000,
    loanAmountMax:       300000,
    interestRatePA:      '15.00',
    tenureMonthsMin:     12,
    tenureMonthsMax:     48,
    processingFeePercent: '1.00',
    targetSegments:      ['salaried', 'self_employed', 'gig'],
    applyUrl:            null,
    description:         'Digital-first personal loans with fast online approval',
    isActive:            true,
  },
  {
    lenderName:          'KreditBee',
    productName:         'Instant Personal Loan',
    productType:         LoanProductType.PERSONAL,
    minScore:            450,
    maxScore:            850,
    minMonthlyIncome:    10000,
    loanAmountMin:       5000,
    loanAmountMax:       200000,
    interestRatePA:      '20.00',
    tenureMonthsMin:     3,
    tenureMonthsMax:     24,
    processingFeePercent: '2.50',
    targetSegments:      ['salaried', 'gig', 'self_employed', 'daily_wage'],
    applyUrl:            null,
    description:         'Short-term personal loans with instant digital disbursal',
    isActive:            true,
  },
];

async function seed() {
  await dataSource.initialize();
  console.log('Connected to database');

  const repo = dataSource.getRepository(LoanProduct);

  // Clear existing seed data so the script is idempotent
  await dataSource.query('DELETE FROM loan_products');
  console.log('Cleared existing loan products');

  const saved = await repo.save(repo.create(PRODUCTS));
  console.log(`✓ Seeded ${saved.length} loan products`);

  await dataSource.destroy();
  process.exit(0);
}

seed().catch((err: unknown) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
